version: '3.3'
services:
  fibonacci:
    build: ./fibonacci-api
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    restart: on-failure

  power:
    build: ./power-api
    ports:
      - "5000:5000"
    depends_on:
      - eureka
    restart: on-failure

  eureka: 
    image: springcloud/eureka
    ports:
      - "8761:8761"

  zuul:
    build: ./zuul
    ports:
      - "8080:8080"
    depends_on:
      - eureka
